apiVersion: v1

kind: Service

metadata:

  name: m5-p1-avance-rest

spec:

  selector:

    app: m5-p1-avance-rest

  ports:

    - protocol: TCP

      port: 80

      targetPort: 8082

  type: LoadBalancer
