apiVersion: rbac.authorization.k8s.io/v1

kind: RoleBinding

metadata:

  name: tekton-rolebinding-2

  namespace: diploe2-dim

subjects:

- kind: ServiceAccount

  name: tekton-sa-2

  namespace: diploe2-dim

roleRef:

  kind: Role

  name: tekton-role-2

  apiGroup: rbac.authorization.k8s.io
