apiVersion: v1

kind: Secret

metadata:

  name: dockerconfig-secret

  namespace: diploe2-dim

stringData:

  config.json: |

    {

      "auths": {

        "https://index.docker.io/v1/": {

          "auth": "ZG9yaWNlbGkuaXh0bGFAZ21haWwuY29tOmRpbWkxNTI4Nw=="

        }

      }

    }
