apiVersion: rbac.authorization.k8s.io/v1

kind: Role

metadata:

  name: tekton-role-2

  namespace: diploe2-dim

rules:

- apiGroups: [""]

  resources: ["pods", "persistentvolumeclaims", "secrets", "configmaps"]

  verbs: ["get", "list", "watch", "create", "update", "delete"]

- apiGroups: ["tekton.dev"]

  resources: ["pipelineruns", "taskruns"]

  verbs: ["get", "list", "watch", "create", "update", "delete"]
