apiVersion: rbac.authorization.k8s.io/v1

kind: Role

metadata:

  name: tekton-role

  namespace: diploe2-dim

rules:

  - apiGroups: [""]

    resources:

      - "pods"

      - "persistentvolumeclaims"

      - "secrets"

      - "configmaps"

    verbs:

      - "get"

      - "list"

      - "watch"

      - "create"

      - "update"

      - "delete"

  - apiGroups: ["apps"]
    
    resources: ["deployments", "deployments/scale"]
    
    verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]

  - apiGroups: ["tekton.dev"] # Controller needs to access these tekton resources

    resources:

      - "pipelineruns"

      - "taskruns"

    verbs:

      - "get"

      - "list"

      - "watch"

      - "create"

      - "update"

      - "delete"


