apiVersion: rbac.authorization.k8s.io/v1

kind: RoleBinding

metadata:

  name: tekton-rolebinding

  namespace: diploe2-dim

subjects:

  - kind: ServiceAccount

    name: tekton-sa

    namespace: default

roleRef:

  kind: Role

  name: tekton-role

  apiGroup: rbac.authorization.k8s.io
