pipeline {

    agent any

    tools {

        maven 'maven'

        jdk 'JDK17'

    }



environment {

        DOCKERHUB_CREDENTIALS = credentials('dim-docker-registry')

        DOCKER_IMAGE = 'doriceli/avance_rest:v5'

}



   stage('Build') {

          steps {

            sh 'sudo docker build -t ${DOCKER_IMAGE} .'

          }

        }

        stage('Login & Push') {

          steps {

                sh '''

                    echo $DOCKERHUB_CREDENTIALS_PSW | sudo docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin docker.io

                    sudo docker push ${DOCKER_IMAGE}

                '''

          }

        }
 }
